config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_page#home'
  get 'static_page/home'
  get '/readings/doya'
  resources :readings, except: :show
  get 'rakuten/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :readings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    rakuten_index_path
  end
end

app/controllers/rakuten_controller.rb
class RakutenController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:word]
      @word = params[:word]
      @items = RakutenWebService::Books::Book.search(title: @word) if @word.present?
    end
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @readings = Reading.where(user_id: current_user.id)
  end

  def new
    @reading = Reading.new(name: params[:name], price: params[:price], user_id: current_user.id)
  end

  def edit
  end

  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to readings_path, notice: 'Reading was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def doya
    @price = Reading.where(user_id: current_user.id).sum(:price)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:name, :price, :user_id)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  / トップページ作成後修正予定
  - if user_signed_in? 
    a.navbar-brand href=rakuten_index_path #{t('appname')} 
  - else
    a.navbar-brand href=root_path #{t('appname')}

  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav.mr-auto
      - if user_signed_in?
        = link_to t('header.search'), rakuten_index_path, class: 'nav-item nav-link'
        = link_to t('header.history'), readings_path, class: 'nav-item nav-link'
    .navbar-nav
      - if user_signed_in?
        = link_to t('header.logout'), destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
      - else
        = link_to t('header.login'), new_user_session_path, class: 'nav-item nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Rakubook
    = csrf_meta_tags
    = csp_meta_tag

    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"

    = render 'layouts/header'
    = yield

app/views/rakuten/_items.html.slim
- if item.present?
  .product-box
    h4.book-title
      = "#{item['title']}"
      br
      = "#{item['itemPrice']} 円"
    img src="#{item['largeImageUrl']}"
    br
    - reading = Reading.new(name: item['title'], price: item['itemPrice'])
    = link_to t('.register'), new_reading_path(name: item['title'], price: item['itemPrice']), class: 'btn btn-primary'

app/views/rakuten/index.html.slim
.container
  h1=t('.title')

  = form_with url: rakuten_index_path, method: :get, local: true, html: {class: 'form-inline'} do |form|
    .form-group = form.text_field :word, class: 'form-control mt-1', placeholder: 'キーワード(書籍名)', value: @word
    = form.submit t('.button'), class: 'btn btn-primary mt-1 ml-1'

  br
  - @items&.first(100)&.each_slice(2) do |item1, item2|
    .row.product-row
      .col
        = render 'items', item: item1
      .col
        = render 'items', item: item2

app/views/readings/_form.html.slim
= form_for @reading do |f|
  .form-group
  - if @reading.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reading.errors.count, "error")} prohibited this reading from being saved:"
      ul
        - @reading.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :user_id
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :price
    = f.number_field :price, class: 'form-control'
  .actions = f.submit t('.button'), class: 'btn btn-primary mb-2'

app/views/readings/doya.html.slim
.container

  = image_tag "doya#{rand(20)}.jpg"
  h1
    = "おれ今月、"
    br
    = "本代に #{@price} 円も使っちゃってさぁ..."
    br
    = "(ドヤァ。。。)"

app/views/readings/edit.html.slim
h1 Editing reading

== render 'form'

=> link_to 'Show', @reading
'|
=< link_to 'Back', readings_path

app/views/readings/index.html.slim
.container
  h1=Reading.model_name.human

  = link_to t('.doya_price'), readings_doya_path, class: 'btn btn-primary'

  table.table.table-hover.mt-2
    thead.thead-light
      tr
        th[scope="col"] = Reading.human_attribute_name(:name)
        th[scope="col"] = Reading.human_attribute_name(:price)
        th[scope="col"]
        th[scope="col"]

    tbody
      - @readings.each do |reading|
        tr
          td = reading.name
          td = reading.price
          td = link_to t('common.edit'), edit_reading_path(reading)
          td = link_to t('common.destroy'), reading, data: { confirm: t('common.confirm') }, method: :delete

app/views/readings/new.html.slim
.container
  h1 = t('.title')

  == render 'form'

  = link_to t('common.back'), readings_path

app/views/static_page/home.html.slim
.top-page
  .jumbotron
    .container-fluid.text-center
      = image_tag "top.png", class: 'img-fluid'
    .text-center
      = link_to t('.link-to-signup'), new_user_registration_path, class: 'btn btn-lg btn-primary'

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to t('user.shared.links.sign_in'), new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t('user.shared.links.sign_up'), new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t('user.shared.links.forgot_your_password'), new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t('user.shared.links.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('user.shared.links.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to t('user.shared.links.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider)
    br